import Container from "@/components/Container";
import Button from "@/components/Button";
import SectionHeading from "@/components/SectionHeading";
import { useI18n } from "@/i18n";

export default function About() {
 const {language}=useI18n(); const ar=language==="ar";
 const traits=ar?[["جزائرية","انطلقت SADCHIRO من الجزائر، ونريد أن تبقى هذه البداية مصدر قوة وهوية."],["مستقلة","نبني منتجاتنا وفق ما تحتاجه المشكلة والمستخدم، لا وفق الضجيج."],["عملية","نفضّل الحل المفيد والواضح على التعقيد والاستعراض."],["مدفوعة بالمنتج","ما نبنيه هو جوهر الشركة، وكل شيء آخر يدعم المنتج."],["حلّ المشكلات","نبدأ من مشاكل حقيقية ومحددة، ثم نبحث عن أبسط حل قابل للاستمرار."],["طموحة عالميًا","نبني من الجزائر مع رؤية تتجاوز حدودها."]]:[["Algerian","SADCHIRO started in Algeria, and that origin remains part of our strength and identity."],["Independent","We make product decisions around real problems and users, not noise."],["Practical","We prefer useful, clear solutions over complexity and spectacle."],["Product-driven","What we build is the core of the company; everything else supports the product."],["Problem-solving","We start with real, specific problems and work toward the simplest durable solution."],["Globally ambitious","We build from Algeria with a vision that reaches beyond it."]];
 return <><section className="rule"><Container className="py-16 md:py-24"><div className="max-w-2xl flex flex-col gap-6"><span className="text-sm font-medium text-clay">{ar?"عن SADCHIRO":"About SADCHIRO"}</span><h1 className="text-4xl md:text-5xl text-pine leading-tight">{ar?"شركة تُبنى بالمنتجات، لا بالوعود.":"A company built on products, not promises."}</h1><p className="text-lg text-charcoal/70 leading-relaxed">{ar?"SADCHIRO شركة تكنولوجية جزائرية مستقلة نبني منتجات رقمية عملية لمشاكل حقيقية. نتحرك بسرعة، لكننا نؤمن أن المنتج الجيد يحتاج وضوحًا وصبرًا.":"SADCHIRO is an independent Algerian technology company building practical digital products for real problems. We move with ambition, while believing good products require clarity and patience."}</p></div></Container></section><section className="rule bg-white"><Container className="py-16 md:py-24"><SectionHeading title={ar?"ما هي SADCHIRO؟":"What SADCHIRO is"}/><div className="mt-10 grid grid-cols-1 gap-8 md:grid-cols-3">{traits.map(([title,text])=><div key={title} className="border-t border-charcoal/15 pt-6"><h3 className="text-lg font-medium text-pine">{title}</h3><p className="mt-2 text-charcoal/70 leading-relaxed">{text}</p></div>)}</div></Container></section><section className="rule"><Container className="grid grid-cols-1 gap-12 py-16 md:grid-cols-2 md:py-24"><div><span className="text-sm font-medium text-clay">{ar?"منهجنا":"Philosophy"}</span><h2 className="mt-4 text-2xl md:text-3xl text-pine">{ar?"العملي قبل المثير للإعجاب.":"Practical over impressive."}</h2><p className="mt-4 text-charcoal/70 leading-relaxed">{ar?"نفضّل إطلاق شيء مفيد يصل إلى الناس اليوم على فكرة رائعة لا تصل إلى أحد. التعقيد يجب أن يكون مبررًا، لا نقطة البداية.":"We would rather ship something useful that reaches people than something impressive that never does. Complexity must be earned, not assumed."}</p></div><div><span className="text-sm font-medium text-clay">{ar?"رؤيتنا":"Vision"}</span><h2 className="mt-4 text-2xl md:text-3xl text-pine">{ar?"من الجزائر إلى العالم.":"From Algeria to the world."}</h2><p className="mt-4 text-charcoal/70 leading-relaxed">{ar?"نريد بناء مجموعة من المنتجات التي تحل مشاكل حقيقية، وربطها تحت SADCHIRO، ثم ترك جودة العمل تتحدث عن الشركة عالميًا.":"We aim to build a family of products that solve real problems, connect them under SADCHIRO, and let the quality of the work speak internationally."}</p></div></Container></section><section className="bg-pine text-ivory"><Container className="flex flex-col items-start gap-6 py-16 md:flex-row md:items-center md:justify-between md:py-24"><div><h2 className="text-2xl md:text-3xl">{ar?"هل تريد معرفة المزيد؟":"Want to know more?"}</h2><p className="mt-2 text-ivory/70">{ar?"يسعدنا أن نتحدث معك.":"We'd be glad to talk."}</p></div><Button to="/contact" variant="primary">{ar?"تواصل معنا":"Get in touch"}</Button></Container></section></>;
}